package client_sharenow;

public enum ServerRequest {
    LOGIN_REQUEST("0"),SIGNUP_REQUEST("1"),FILE_FETCH_REQUEST("2"),FILE_ADD_REQUEST("3")/*,RETAILER_REGISTRATION("2"),CATEGORIES("3"),FILE_FETCH_REQUEST("4"),FILE_ADD_REQUEST("5"),PRODUCT_EDIT_REQUEST("6"),PRODUCT_DELETE_REQUEST("7"),RETAILER_LOGIN("8"),PRODUCT_BUY_REQUEST("9"),*/
    /*MONEY_SPEND_REQUEST("10"),OFFER_ADD_REQUEST("11")*/,ADMIN_LOGIN_REQUEST("4"),USER_FETCH_REQUEST("5")/*,TRANSACTION_FETCH_REQUEST("14"),CATEGORY_ADD_REQUEST("15"),CATEGORY_REMOVE_REQUEST("16"),OFFER_REQUEST("17")*/
    /*,RETAILER_FETCH_REQUEST("18"),ANALYZE_CATEGORY_REQUEST("19"),ANALYZE_USER_REQUEST("20"),EXTRA_OFFER_SET_REQUEST("21")*/;


    ServerRequest(String s) {
        this.toString();
    }
}
